all:
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  hosts:
    node-1:
      ansible_host: 192.168.20.2
    node-2:
      ansible_host: 192.168.20.3
    node-3:
      ansible_host: 192.168.20.4
  children:
    app:
      hosts:
        node-1:
        node-2:
    db:
      hosts:
        node-3: