# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "256"
    vb.linked_clone = true
  end
  
  (1..3).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "node#{i}.dev"
      node.vm.network :private_network, ip: "192.168.20.#{i+1}"
    end

  end

end
